### ISSUE TITLE
Issue Its uptobox and uptostream

### ISSUE THREAD

**Issue by RedRaph85** [ddurdle/CloudStream-for-KODI#11]
Streams from uptobox or upsostream no longer work.

plugin://plugin.video.cloudstream?mode=streamURL&url=http://uptostream.com/lewes7o5on12

**Comment by sarped0n** [comment]
Hello,

I found this plugin for Kodi yesterday and there is a problem with uptobox. But I found the solution in order to correct it. In fact Uptobox has modified the way users can connect on their website and they also changed some html pages. So the scrapper used in this plugin just need an update. I made a quick correction yesterday and it was working well for uptobox. It streams the raw file with the possibility to change language, subtitles (if included in the video), etc... 

Concerning uptostream, links are different for each configuration. If you have for example two languages : french and English and a 1080p video, Uptostream will create 3 or 4 links for french (1080p, 720p, 5xxp and 360p) and 3 or 4 links for English. So it is a bit harder to modify the plugin in order to allow the choice of the link we want. an upgrade has to be done for that.

I will try to do the "final version" for uptobox this evening and I will post it here.

And by the way, very good work ddurdle. This plugin is really great.

**Comment by ddurdle** [comment]
Thank you for the contribution.  I eagerly await the update.  

It might be easier to integrate the functionality I have to allow user to be prompted for a stream selection like in the Google Drive plugin.  There is also logic to pre-select a choice based on preferences.

**Comment by sarped0n** [comment]
Ok, here is my file and just to warn you :  I am a total beginner in Python.
[xfilesharing.zip](https://github.com/ddurdle/CloudStream-for-KODI/files/131376/xfilesharing.zip)

Lines modified : 
around line 77 : new url is : https://login.uptobox.com/log
around line 84 : redirect url commented
around line 250 : modified the filter :  td a href
around line 756 : streamURL = 'http:' + r.group(1)

I am sure it is not perfect but for me it is working !

**Comment by ddurdle** [comment]
thank you for the contribution, it has been added to 0.3.0 build

http://dmdsoftware.net/repository.ddurdle/plugin.video.cloudstream-0.3.0.zip

**Comment by sarped0n** [comment]
Hello,

There is a bug. Il will try to look at it this week-end. But it is on the file I sent to you. When using a strm file it is working but when I use the add on itself it doens't work. And in version 0.3.0 the is a spash screen with "incorrect login".

**Comment by Snammx** [comment]
Hello,

i have incorrect login for uptobox/uptostream premium with the last version (19-02-2016). You too sarped0n? its work for you? Thx , if this plugin work its was "amazing"!

**Comment by ddurdle** [comment]
I will test with my account and report back in next 24 hours.

**Comment by ddurdle** [comment]
My website is out of bandwidth/out of money.  I've hosted it on this other site.  Repository won't auto-update until there is more bandwidth, so you will need to install manually.

Fixed in 0.3.1
http://dmdsoftware.com/repository-ddurdle/plugin.video.cloudstream-0.3.1.zip

**Comment by RedRaph85** [comment]
Hey Guys!! good job with the Update! the stream from uptobox and uptostream work good ! :)

Do we know if we can add support for Tusfiles.net?

**Comment by ddurdle** [comment]
Some users are reporting odd issue with uptobox in the plugin.  Certain devices like a phone, it'll fail over wifi but work over data OR work over data and not over wifi.  

If anyone is in this situation, let me know as I need more log information.

**Comment by ddurdle** [comment]
I moved request for tusfiles.net to https://github.com/ddurdle/CloudStream-for-KODI/issues/12

**Comment by kikimmax** [comment]
Merci Beaucoup

**Comment by RedRaph85** [comment]
Hello Everyone,

Just to give a head up,

Stream from http://uptobox is working fine but if you try with a .strm file that has http://uptostream the link will not play. was working fine until yesterday!

Thanks!!

**Comment by itsspecialk** [comment]
Hey everyone, cloudstream is my fav add-ons and I know a lot of friends that use it everyday. A lot of us use it with uptobox and they made changes to their website. I am able to log in and see my files but I am not able to stream any of my video. Anyone able to help? Is there somewhere that I can learn how to make fixes if there is a bug?

Thanks again for all the help!!

**Comment by sarped0n** [comment]
Hello,

I am not at home right now but I tested remotely and you're right. I will look at it this next week. I was still using the 2.7 version I modified myself and I also have the problem. I will keep you informed.

**Comment by ddurdle** [comment]
I will investigate

**Comment by sarped0n** [comment]
The part to be updated is the file : xfilesharing.py

And as you say only the streaming does not work (me I am only using the streaming part), there should be something to do on the filter part at the end of the file :
elif self.domain == 'uptobox.com' or self.domain == 'uptostream.com':

            for r in re.finditer('\<a href\=\"([^\"]+)\"\>\s+\<span class\=\"button_upload green\"\>',
                             response_data, re.DOTALL):
                  streamURL = r.group(1)
                  fname = re.sub('Download ', '', fname)

                  return (streamURL, fname)

**Comment by itsspecialk** [comment]
I took a look and i have no idea what I'm looking at! When you figure it out mind sharing tutorial?  When it comes to uptobox website, when you clicked on a video link it would ask you after if you want to generate a download link or a stream link. Now it shows you a click to download and for streaming you press play on the video image. Not sure if this info helps.

**Comment by itsspecialk** [comment]
Hey i downloaded the updated cloudstream master zip and in order to have a stream start working again i had to uninstall older version and remove it from  userdata /addon_data. I reinstalled it and then i was good to go.
Thanks for the help!! I guess the update will push on its own?

**Comment by ddurdle** [comment]
Yes, the update has been pushing down from the repository.

**Comment by RedRaph85** [comment]
Hello Everyone,

There seems to be a new issue with uptobox again. I am able to add in my username and Pw however when ever i try to go into the addon it tells me ''Login information is incorrect or Permission is denied''. Whats funny is that after you click ok i am able to stream .strm file from uptobox with that error message but not able to access my account and see all my file.  The addon was working fine 2 days ago and i did not make any changes to my user name and Pw.

Thanks!

**Comment by ddurdle** [comment]
It could be related to some new change recently made.  This morning I saw some users of other uptobox apps complaining the apps stopped working today .

**Comment by fant4sy92** [comment]
Hello everyone,

update? :(
Thanks!

**Comment by sarped0n** [comment]
Hello,

In vstream, they found a way to connect to uptobox. I tried to adapt the code to cloudstream but my level is too low to do it.
Here is the link of the new file : https://github.com/Kodi-vStream/venom-xbmc-addons/blob/Beta/plugin.video.vstream/resources/lib/handler/premiumHandler.py

**Comment by schroef** [comment]
WTF is this Uptobox.... NOthing works now in Kodi. Each time this thing popsup with every movie i click?!
