### ISSUE TITLE
Uptobox/Uptostream

### ISSUE THREAD

**Issue by Bigups23** [ddurdle/CloudStream-for-KODI#13]
Hello

This plug doesn't works, when i click it it seems to be an error

Videos > Extension>Cloudstream   dosen't works 

version 0.3.2 ddurdle

**Comment by ddurdle** [comment]
I will have a look.

**Comment by Bigups23** [comment]
Ok thanks !

**Comment by ddurdle** [comment]
you need to setup an account in settings.
