### ISSUE TITLE
UptoBox Not working

### ISSUE THREAD

**Issue by maximilianh75** [ddurdle/CloudStream-for-KODI#17]
I'm using kodi krypton  7.3 with cloudstream 0.3.6 from official repo and UPTOBOX premium account not working anymore with addon
Any idea what happening
To be more specific
 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.cloudstream/?

**Comment by itsspecialk** [comment]
Hey everyone, uptobox updated their website and add-ons no longer works even if you have a uptobox account. Looking for some help! Thanks:)

**Comment by ddurdle** [comment]
Latest version fixes this issue.

See Patch for issue #11 #20
Issue Its uptobox and uptostream #11
