### ISSUE TITLE
Error when runing script

### ISSUE THREAD

**Issue by Pooky** [ddurdle/CloudStream-for-KODI#8]
Hello,

I get error when I try to install this script.  I check the log and it seems like some error in Python code.
Is there any fix or older working version of code?
```
20:46:04 T:2896657216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'str' object has no attribute 'getVideosList'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/CloudStream-for-KODI-master/default.py", line 233, in <module>
                                                videos = cloudservice.getVideosList(folderID=folderID)
                                            AttributeError: 'str' object has no attribute 'getVideosList'
                                            -->End of Python script error report<--
```

**Comment by ddurdle** [comment]
Which service are you using?

**Comment by Pooky** [comment]
I want use streamcloud.eu, I cant find it predefined, so I choose Custom and put login info.

**Comment by ddurdle** [comment]
I'll add logic to capture when people add a site through custom that has issues using the default capture mechanisms so that they understand that is issue and how to get help to add support.

I'll add support for this site right now.  If it goes well, a build should be working today.

**Comment by ddurdle** [comment]
Supported added to 0.2.1 - http://dmdsoftware.net/repository.ddurdle/plugin.video.cloudstream-0.2.1.zip

**Comment by Pooky** [comment]
Hi ddurdle,

thanks for that fix. I tried that and now I setup streamcloud.eu from supported hosters, but I get error after that.

When I try to run this plugin, it says that there are no account setup (even thought that I setup streamcloud.eu), when I setup another account - same as the first one (so two accounts) then I get to first list, to pick account and then again is there error says - "Please setup a service in Addon-Settings->Account".

Any idea how to fix that? :) 

Thanks
Martin

**Comment by ddurdle** [comment]
Can you try version 0.2.2?

The only reason this service nerve worked originally was because there is a
mandatory 10 second wait, otherwise it errors.  The site would HV worked
with custom prior if I had provide an option to provide a wait time.

**Comment by Pooky** [comment]
Where I can get 0.2.2. version? I use last code directly from github - and there is last version 0.2.1.

**Comment by ddurdle** [comment]
Try here:

http://dmdsoftware.net/repository.ddurdle/plugin.video.cloudstream-0.2.2.zip

And the repository for auto-updates is here:
http://dmdsoftware.net/repository.ddurdle/repository.ddurdle.zip

**Comment by ddurdle** [comment]
new version:   http://dmdsoftware.net/repository.ddurdle/plugin.video.cloudstream-0.2.4.zip

**Comment by ddurdle** [comment]
some more improvements: http://dmdsoftware.net/repository.ddurdle/plugin.video.cloudstream-0.2.5.zip

**Comment by Pooky** [comment]
Hi, thanks for improvement, I'm now on holidays, but I will give it try when I come back :)

**Comment by ddurdle** [comment]
Just make sure you install the latest version at the time you get around to it.  You can also install the repository and it will update to the latest version.

I'm on holidays in 2 weeks and I intend to whip up the plugin a bit.

**Comment by Pooky** [comment]
It work really well! Thanks. This latest version fix all problems that I had.

**Comment by ddurdle** [comment]
I appreciate the followup.  If there is any other issues or features required, let me know, anytime.

**Comment by Pooky** [comment]
It works pretty well, but when you already asked :P 

I can play every video from my folder, but it would be really handy, if this application could play video from public URL like this - http://streamcloud.eu/c1i49abnqqgc/S01E05_Bart_schlaegt_eine_Schlacht__BB_.avi  - it would be also cool, if it could read .txt file with coma delimetered format - where first would be "Video name", "URL"  meaby "Hoster?" and then you could just tell way on disk and it would show up list of videos and you can play any of this video.

**Comment by ddurdle** [comment]
Maybe what you need is already there.  You can create .STRM files on disk that when invoked will playback via the plugin the URL specified.  Further, these could be .M3U files that contain a list of multiple streams to playback, in sequence.

For example, I test with the following two files:

**Comment by ddurdle** [comment]
streamcloud.eu.2.strm

**Comment by ddurdle** [comment]
streamcloud.eu.2.strm
plugin.video.cloudstream?mode=streamURL&url=http://streamcloud.eu/3szp480ou9cr/Sintel_DivXPlus_6500kbps.mkv.html

streamcloud.eu.strm
plugin://plugin.video.cloudstream?mode=streamURL&url=http://streamcloud.eu/adr5rrg2vjjk/Abnorm_23_____Fick_Mich_Wenn_ich_Pisse.flv.html

**Comment by Pooky** [comment]
OK, and how can I invoke (run) from KODI this file?

**Comment by ddurdle** [comment]
Under Video -> Files.  For example, store your .STRM files in a directory
on your KODI device, then add that path to Video -> Files -> Add Videos.
If your .STRM files represent valid movie names ("movie title
(year).strm"), they'll even be importable into the KODI library from
Movies).

I don't yet provide an automated means of creating .STRM files
automatically in CloudStream, like I do in other plugins, but this video I
made for Hive.IM plugin demonstrates near the end of the video how to
playback .STRM files https://www.youtube.com/watch?v=mf8KR7QBUZA

**Comment by Pooky** [comment]
OK, I done it, but it says "Can't find a next item to play", what can I do about that? Do I need more links?

**Comment by ddurdle** [comment]
What does the contents of your file look like?  It should be one line such as one below.

plugin.video.cloudstream?mode=streamURL&url=http://streamcloud.eu/3szp480ou9cr/Sintel_DivXPlus_6500kbps.mkv.html

**Comment by Pooky** [comment]
Yep, I copy and paste this line there...
 

 

 

-----Ursprüngliche Mitteilung----- 
Von: ddurdle <notifications@github.com>
An: ddurdle/CloudStream-for-KODI <CloudStream-for-KODI@noreply.github.com>
Cc: Martin Klíma <martin.klima@aol.com>
Verschickt: Fr, 14 Aug 2015 7:56 pm
Betreff: Re: [CloudStream-for-KODI] Error when runing script (#8)


 
What does the contents of your file look like? It should be one line such as one below.
  
plugin.video.cloudstream?mode=streamURL&url=http://streamcloud.eu/3szp480ou9cr/Sintel_DivXPlus_6500kbps.mkv.html

**Comment by Pooky** [comment]
There is log file with error:

22:54:58 T:2944232256   ERROR: CDVDPlayer::OpenInputStream - error opening [plugin.video.cloudstream?mode=streamURL&url=http://streamcloud.eu/3szp480ou9cr/Sintel_DivXPlus_6500kbps.mkv.html]
22:54:58 T:2944232256  NOTICE: CDVDPlayer::OnExit()
22:54:58 T:3001775936   ERROR: Playlist Player: skipping unplayable item: 1, path [plugin.video.cloudstream?mode=streamurl&url=http://streamcloud.eu/3szp480ou9cr/Sintel_DivXPlus_6500kbps.mkv.html]
22:54:58 T:3001775936  NOTICE: CDVDPlayer::CloseFile()
