### ISSUE TITLE
timeout issue using Vodlocker.com

### ISSUE THREAD

**Issue by patman2** [ddurdle/CloudStream-for-KODI#9]
I get a timeout issue when trying to see videos on vodlocker.com.  There needs to be a 3 second timeout after a video is opened.  Even when using a web browser, there is a 3 second timeout before video can be played.  As it is now, I can see files, but can't play them because of this 3 second timeout issue.
Thanks in advance

**Comment by ddurdle** [comment]
It should already be timing out for 3 seconds:

        elif self.domain == 'vodlocker.com':
            xbmcgui.Dialog().ok(ADDON.getLocalizedString(30000), ADDON.getLocalizedString(30037) + str(3))
            xbmc.sleep((int(3)+1)*1000)

**Comment by ddurdle** [comment]
cannot reproduce.  tried 1 public video and 1 private video.  both played back.

I recommend you make sure you are running the latest version http://dmdsoftware.net/repository.ddurdle/plugin.video.cloudstream-0.2.7.zip
